config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'  
  
  get 'home/index'
  resources :firms
  resources :services
  resources :clients
  
  get 'auth/auth0/callback' => 'auth0#callback'
  get 'auth/failure' => 'auth0#failure'
  get '/logout' => 'logout#logout'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/firm.rb
class Firm < ApplicationRecord

  validates :first_name, presence: true, length: { maximum: 60 }
  validates :middle_name, length: { maximum: 60 }
  validates :last_name, presence: true, length: { maximum: 60 }
  validates :maiden_name, length: { maximum: 60 }
  validates :dob,
            format: {with: %r{\A\d{2}-\d{2}-\d{4}\Z}},
            presence: true
  validates :ssn,
            format: {with: %r{\A\d{3}-\d{2}-\d{4}\Z}}
            #,uniqueness: {case_sensitive: false}
  validates :dl_number, length: { maximum: 40 }
  validates :dl_state,
            format: {with: %r{\A\w{2}\Z}}
  validates :notes, length: { maximum: 100 }
end

app/controllers/firms_controller.rb
class FirmsController < ApplicationController
  before_action :set_firm, only: %i[ show edit update destroy ]

  # GET /firms or /firms.json
  def index
    @firms = Firm.all
    return @firms
  end

  # GET /firms/1 or /firms/1.json
  def show
  end

  # GET /firms/new
  def new
    @firm = Firm.new
  end

  # GET /firms/1/edit
  def edit
  end

  # POST /firms or /firms.json
  def create
    @firm = Firm.new(firm_params)

    respond_to do |format|
      if @firm.save
        format.html { redirect_to @firm, notice: "Firm was successfully created." }
        format.json { render :show, status: :created, location: @firm }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @firm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /firms/1 or /firms/1.json
  def update
    respond_to do |format|
      if @firm.update(firm_params)
        format.html { redirect_to @firm, notice: "Firm was successfully updated." }
        format.json { render :show, status: :ok, location: @firm }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @firm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /firms/1 or /firms/1.json
  def destroy
    @firm.destroy
    respond_to do |format|
      format.html { redirect_to firms_url, notice: "Firm was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_firm
      @firm = Firm.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def firm_params
      params.require(:firm).permit(:invoice_data, :first_name, :middle_name, :last_name, :maiden_name, :dob, :ssn, :dl_state, :dl_number, :notes, :client_request)
    end
end

app/helpers/firms_helper.rb
# :nocov:
module FirmsHelper
end
# :nocov:

app/views/firms/_form.html.erb
<div class="container-fluid">
  <%= form_with(model: firm, local: true) do |form| %>
    <% if firm.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(firm.errors.count, "error") %> prohibited this firm from being saved:</h2>

        <ul>
          <% firm.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>


    


    <div class="field mb-3">
      <%= form.label :invoice_data, class:"form-label" %>
      <%= form.text_field :invoice_data, class:"form-control" %>
    </div>

    <div class="field mb-3">
      <%= form.label :first_name, class:"form-label" %>
      <%= form.text_field :first_name, class:"form-control" %>
    </div>

    <div class="field mb-3">
      <%= form.label :middle_name, class:"form-label" %>
      <%= form.text_field :middle_name, class:"form-control" %>
    </div>

    <div class="field mb-3">
      <%= form.label :last_name, class:"form-label" %>
      <%= form.text_field :last_name, class:"form-control" %>
    </div>

    <div class="field mb-3">
      <%= form.label :maiden_name, class:"form-label" %>
      <%= form.text_field :maiden_name, class:"form-control" %>
    </div>

    <div class="field mb-3">
      <%= form.label :dob, class:"form-label" %>
      <%= form.text_field :dob, class:"form-control" %>
    </div>

    <div class="field mb-3">
      <%= form.label :ssn, class:"form-label" %>
      <%= form.text_field :ssn, class:"form-control" %>
    </div>

    <div class="field mb-3">
      <%= form.label :dl_state, class:"form-label" %>
      <%= form.text_field :dl_state, class:"form-control" %>
    </div>

    <div class="field mb-3">
      <%= form.label :dl_number, class:"form-label" %>
      <%= form.text_field :dl_number, class:"form-control" %>
    </div>

    <div class="field mb-3">
      <%= form.label :notes, class:"form-label" %>
      <%= form.text_field :notes, class:"form-control" %>
    </div>

    <div class="field mb-3">
      <%= form.label :client_request, class:"form-label" %>
      <%= form.text_field :client_request, class:"form-control" %>
    </div>

    <div class="actions mb-3">
      <%= form.submit "Create Request", class:"btn btn-primary" %>
      <i class="fas fa-paper-plane"></i>
    </div>
  <% end %>
</div>

app/views/firms/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', firm: @firm %>

<%= link_to 'Show', @firm, class:"btn btn-dark" %> |
<%= link_to 'Back', firms_path, class:"btn btn-dark" %>

app/views/firms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Requests</h1>

<table class="table table-primary table-striped">
  <thead>
    <tr>
      <th>Invoice data</th>
      <th>First name</th>
      <th>Middle name</th>
      <th>Last name</th>
      <th>Maiden name</th>
      <th>Dob</th>
      <th>Ssn</th>
      <th>Dl state</th>
      <th>Dl number</th>
      <th>Notes</th>
      <th>Client request</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @firms.each do |firm| %>
      <tr>
        <td><%= firm.invoice_data %></td>
        <td><%= firm.first_name %></td>
        <td><%= firm.middle_name %></td>
        <td><%= firm.last_name %></td>
        <td><%= firm.maiden_name %></td>
        <td><%= firm.dob %></td>
        <td><%= firm.ssn %></td>
        <td><%= firm.dl_state %></td>
        <td><%= firm.dl_number %></td>
        <td><%= firm.notes %></td>
        <td><%= firm.client_request %></td>
        <td><%= link_to 'Show', firm %></td>
        <td><%= link_to 'Edit', edit_firm_path(firm) %></td>
        <td><%= link_to 'Destroy', firm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_firm_path, class:"btn btn-primary" %>

app/views/firms/new.html.erb
<h1>New Request</h1>

<%= render 'form', firm: @firm %>

<%= link_to 'Back', firms_path, class:"btn btn-dark" %>

app/views/firms/show.html.erb
<p id="notice"><%= notice %></p>

<!--<p>-->
<!--  <strong>Invoice Data:</strong>-->
  <%#= @firm.invoice_data %>
<!--</p>-->

<!--<p>-->
<!--  <strong>First Name:</strong>-->
  <%#= @firm.first_name %>
<!--</p>-->

<!--<p>-->
<!--  <strong>Middle Name:</strong>-->
  <%#= @firm.middle_name %>
<!--</p>-->

<!--<p>-->
<!--  <strong>Last Name:</strong>-->
  <%#= @firm.last_name %>
<!--</p>-->

<!--<p>-->
<!--  <strong>Maiden Name:</strong>-->
  <%#= @firm.maiden_name %>
<!--</p>-->

<!--<p>-->
<!--  <strong>DOB:</strong>-->
  <%#= @firm.dob %>
<!--</p>-->

<!--<p>-->
<!--  <strong>SSN:</strong>-->
  <%#= @firm.ssn %>
<!--</p>-->

<!--<p>-->
<!--  <strong>Dl State:</strong>-->
  <%#= @firm.dl_state %>
<!--</p>-->

<!--<p>-->
<!--  <strong>Dl Number:</strong>-->
  <%#= @firm.dl_number %>
<!--</p>-->

<!--<p>-->
<!--  <strong>Notes:</strong>-->
  <%#= @firm.notes %>
<!--</p>-->

<!--<p>-->
<!--  <strong>Client Request:</strong>-->
  <%#= @firm.client_request %>
<!--</p>-->

<dl class="row">
  <dt class="col-sm-3">Name:</dt>
  <dd class="col-sm-9"><%= @firm.first_name %> <%= @firm.last_name %></dd>
  <dt class="col-sm-3">Invoice Data:</dt>
  <dd class="col-sm-9"><%= @firm.invoice_data %></dd>
  <dt class="col-sm-3">DOB:</dt>
  <dd class="col-sm-9"><%= @firm.dob %></dd>
  <dt class="col-sm-3">SSN:</dt>
  <dd class="col-sm-9"><%= @firm.ssn %></dd>
  <dt class="col-sm-3">DL State:</dt>
  <dd class="col-sm-9"><%= @firm.dl_state %></dd>
  <dt class="col-sm-3">DL Number:</dt>
  <dd class="col-sm-9"><%= @firm.dl_number %></dd>
  <dt class="col-sm-3">Notes:</dt>
  <dd class="col-sm-9"><%= @firm.notes %></dd>
  <dt class="col-sm-3">Client Request:</dt>
  <dd class="col-sm-9"><%= @firm.client_request %></dd>
</dl>

<%= link_to 'Edit', edit_firm_path(@firm), class:"btn btn-dark" %> |
<%= link_to 'Back', firms_path, class:"btn btn-dark" %>