config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'  
  
  get 'home/index'
  resources :firms
  resources :services
  resources :clients
  
  get 'auth/auth0/callback' => 'auth0#callback'
  get 'auth/failure' => 'auth0#failure'
  get '/logout' => 'logout#logout'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord

  validates :client_name, length: { maximum: 40 }, presence: true
  validates :company, length: { maximum: 60 }
  validates :address, length: { maximum: 100 }
  validates :city, length: { maximum: 40 }
  validates :state,
            format: {with: %r{\A\w{2}\Z}}
  validates :zip,
            format: {with: %r{\A\d{5}\Z}}
  validates :phone,
            format: {with: %r{\A\d{3}-\d{3}-\d{4}\Z}}
  validates :fax,
            format: {with: %r{\A\d{3}-\d{3}-\d{4}\Z}}
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP },
            presence: true,
            length: {maximum: 40}
            #,uniqueness: {case_sensitive: false}
  validates :notes, length: { maximum: 140 }
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:client_name, :status, :total_requests, :company, :email, :address, :city, :state, :zip, :phone, :fax, :notes, :client_id)
    end
end

app/helpers/clients_helper.rb
# :nocov:
module ClientsHelper
end
# :nocov:

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<!--Form inspired by: https://getbootstrap.com/docs/4.0/examples/checkout/ -->
<body class="bg-light">

    <div class="container">
      <div class="py-5 text-center">
        <h1>New Client</h1>
        <p class="lead">New Client Form</p>
      </div>


          <h4 class="mb-3">Contact Information</h4>
            <hr class="mb-4">
            <div class="row">
              <div class="col-md-6 mb-3">
                <%= form.label :client_name, class:"form-label" %>
                <%= form.text_field :client_name, type: 'text', class: 'form-control'%>
              </div>

              <div class="col-md-6 mb-3">
                <%= form.label :company, class:"form-label" %>
                <%= form.text_field :company, type: 'text', class: 'form-control'%>
              </div>

            </div>

            <div class="row">
              <div class="col-md-6 mb-3">
                <%= form.label :phone, class:"form-label" %>
                <%= form.text_field :phone, type: 'text', class: 'form-control'%>
              </div>
              <div class="col-md-6 mb-3">
                <%= form.label :fax, class:"form-label" %>
                <%= form.text_field :fax, type: 'text', class: 'form-control'%>
              </div>
            </div>

            <div class="mb-3">
              <%= form.label :email, class:"form-label" %>
              <%= form.text_field :email, type: 'text', class: 'form-control'%>
            </div>

            <div class="mb-3">
              <%= form.label :address, class:"form-label" %>
              <%= form.text_field :address, type: 'text', class: 'form-control'%>
            </div>

            <div class="row">
              <div class="col-md-5 mb-3">
                <%= form.label :city, class:"form-label" %>
                <%= form.text_field :city, type: 'text', class: 'form-control'%>
              </div>
              <div class="col-md-4 mb-3">
                <%= form.label :state, class:"form-label" %>
                <%= form.text_field :state, type: 'text', class: 'form-control'%>
              </div>
              <div class="col-md-3 mb-3">
                <%= form.label :zip, class:"form-label" %>
                <%= form.text_field :zip, type: 'text', class: 'form-control'%>
              </div>
            </div>

               <div class="col-md-4 mb-3">
                 <%= form.label :client_id, class:"form-label" %> ID
                  <%= form.number_field :client_id, class: 'form-control'%>
                </div>
            
           
             
            <hr class="mb-4">

            <h4 class="mb-3">Additional Information</h4>
            <div class="row">
            <div class="mb-3">
              <%= form.label :notes, class:"form-label" %>
              <%= form.text_field :notes, class: 'form-control' %>
            </div>
          </div>
          <div class="col-md-4 mb-3">
              <%= form.label :total_requests, class:"form-label" %>
              <%= form.number_field :total_requests, class: 'form-control' %>
            </div>
          <div class="col-md-4 mb-3">
              <%= form.check_box :status %>
              <%= form.label :status, class:"form-label" %>
            </div>

          <hr class="mb-4">


</body>

       <div class="actions mb-3">
      <!-- https://stackoverflow.com/questions/13167535/how-to-put-icon-in-rails-submit-button -->
      <%= button_tag( :class => "btn btn-primary") do %>
        Save Client <i class="fas fa-paper-plane"></i>
      <% end %>
      <!-- <%= form.submit class:"btn btn-primary" %>
      <i class="fas fa-paper-plane"></i> -->
    </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table class="table table-striped table-info">
  <thead>
    <tr>
      <th scope="col">Client Name </th>
      <th scope="col">Company </th>
      <th scope="col">Email </th>
      <th scope="col">Phone </th>
      <th scope="col">Fax </th>
      <th scope="col">Address </th>
      <th scope="col">City </th>
      <th scope="col">State </th>
      <th scope="col">Zip </th>
      <th scope="col">Client ID </th>
      <th scope="col">Status </th>
      <th scope="col">Notes </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.client_name %></td>
        <td><%= client.status %></td>
        <td><%= client.total_requests %></td>
        <td><%= client.company %></td>
        <td><%= client.email %></td>
        <td><%= client.address %></td>
        <td><%= client.city %></td>
        <td><%= client.state %></td>
        <td><%= client.zip %></td>
        <td><%= client.phone %></td>
        <td><%= client.fax %></td>
        <td><%= client.notes %></td>
        <td><%= client.client_id %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client name:</strong>
  <%= @client.client_name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @client.status %>
</p>

<p>
  <strong>Total requests:</strong>
  <%= @client.total_requests %>
</p>

<p>
  <strong>Company:</strong>
  <%= @client.company %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @client.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @client.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @client.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @client.zip %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @client.phone %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @client.fax %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @client.notes %>
</p>

<p>
  <strong>Client:</strong>
  <%= @client.client_id %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>