config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'  
  
  get 'home/index'
  resources :firms
  resources :services
  resources :clients
  
  get 'auth/auth0/callback' => 'auth0#callback'
  get 'auth/failure' => 'auth0#failure'
  get '/logout' => 'logout#logout'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
# :nocov:
class HomeController < ApplicationController
  def index
  end
end
# :nocov:

app/helpers/home_helper.rb
# :nocov:
module HomeHelper
end
# :nocov:

app/views/home/_navbar.html.erb
<!-- https://getbootstrap.com/docs/5.0/components/navs-tabs/ -->
<nav class="nav nav-pills flex-column flex-sm-row">
  <!-- <a class="flex-sm-fill text-sm-center nav-link active" aria-current="page" href="#">Home</a> -->
  <%= link_to 'Talon Agency', root_path, class:"flex-sm-fill text-sm-center nav-link active", 'aria-current' => "page" %>
  <!-- <a class="flex-sm-fill text-sm-center nav-link" href="#">Longer nav link</a> -->
  <%= link_to 'Services', services_path, class:"flex-sm-fill text-sm-center nav-link"%>
  <!-- <a class="flex-sm-fill text-sm-center nav-link" href="#">Link</a> -->
  <%= link_to 'Clients', clients_path, class:"flex-sm-fill text-sm-center nav-link"%>
  <%= link_to 'Requests', firms_path, class:"flex-sm-fill text-sm-center nav-link"%>
  <!-- <a class="flex-sm-fill text-sm-center nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a> -->
</nav>

app/views/home/index.html.erb
<div class="container-fluid center">
  <!--<section class="  image_insert">-->
  <% if user_signed_in? %>
    <%= link_to 'Logout', '/users/sign_out',  class: 'flex-sm-fill text-sm-center nav-link', 'aria-current' => "page" %>
  <% else %>
    <%= link_to 'My Login', '/users/sign_in', method: :post, class: 'flex-sm-fill text-sm-center nav-link', 'aria-current' => "page" %>
  <% end %>
  <%= session[:userinfo].inspect %>
  <br>
  <div class="row">
    <div class="col-md-12">
      <h1 class="h2 text-center">Welcome to Talon Agency | 800-501-3256</h1>
    </div>
  </div>
  <hr style="border: 2px outset #595955;">
  <div class="text-center">
    <img width="30%" height="30%" src="/american-eagle.jpg">
  </div>
  <br />
  <h3 class="text-center lead" >We provide the most comprehensive background checks in the US.</h3><br>
</div>